DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS diet CASCADE;
DROP TABLE IF EXISTS recipe CASCADE;
DROP TABLE IF EXISTS ingredient CASCADE;
DROP TABLE IF EXISTS recipe_ingredient;
DROP TABLE IF EXISTS user_inventory;

